export const FETCH_CITIES = 'FETCH_CITIES';
export const SEARCH = 'SEARCH';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const FETCH_CITY = 'FETCH_CITY';

export const FETCH_ITINERARIES = 'FETCH_ITINERARIES';
export const IT_FETCHING = 'IT_FETCHING';

export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS ='LOGOUT_SUCCESS'
export const REGISTER_SUCESS ='REGISTER_SUCESS'
export const REGISTER_FAIL ='REGISTER_FAIL'
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

