export const FETCH_CITIES = 'FETCH_CITIES';
export const SEARCH = 'SEARCH';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const FETCH_CITY = 'FETCH_CITY';

export const FETCH_ITINERARIES = 'FETCH_ITINERARIES';
export const IT_FETCHING = 'IT_FETCHING';
export const NEW_ITINERARY = 'NEW_ITINERARY';
export const CREATION_SUCCESS = 'CREATION_SUCCESS';
export const CREATION_FAIL = 'CREATION_FAIL';
export const CREATION_RESET = 'CREATION_RESET'

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS ='LOGOUT_SUCCESS';
export const REGISTER_SUCESS ='REGISTER_SUCESS';
export const REGISTER_FAIL ='REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const CO_FETCHING = 'CO_FETCHING';
export const CO_FETCHED = 'CO_FETCHED';
export const NEW_COMMENT = 'NEW_COMMENT';
export const NEW_COMMENT_SUCCESS = 'NEW_COMMENT_SUCCESS';
export const NEW_COMMENT_FAIL = 'NEW_COMMENT_FAIL';
export const NEW_COMMENT_RESET = 'NEW_COMMENT_RESET';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'

